version: "3"


services:
  server:
    build: server/
    command: python server.py
    ports:
      - "10000:10000"

  client:
    build: client/
    command: python client.py
    depends_on:
      - server